### ISSUE TITLE
Cannot add JoystickComponent

### ISSUE THREAD

**Issue by daniel-mf** [ASGAlex/flame_spatial_grid#1]
I've been playing around with this package when I found a problem with `JoystickComponent`.
When I add it to any components like game, world or camera hud children, I got the following error:

```
'dart:ui/painting.dart': Failed assertion: line 5401 pos 12: '<optimized out>': is not true.
When the exception was thrown, this was the stack: 
#2      Canvas.drawImageRect (dart:ui/painting.dart:5401:12)
#3      Sprite.render (package:flame/src/sprite.dart:121:12)
#4      SpriteComponent.render (package:flame/src/components/sprite_component.dart:123:13)
#5      Component.renderTree (package:flame/src/components/core/component.dart:514:5)
#6      Transform2DDecorator.apply (package:flame/src/rendering/transform2d_decorator.dart:21:9)
#7      Decorator.applyChain (package:flame/src/rendering/decorator.dart:38:5)
#8      PositionComponent.renderTree (package:flame/src/components/position_component.dart:463:15)
#9      HasGridSupport.renderTree (package:flame_spatial_grid/src/components/has_grid_support.dart:222:13)
```

The error is a bit blurred (maybe because of [this](https://github.com/dart-lang/sdk/issues/34586)), but when we go to `painting.dart:5401:12` we find this:

```dart
  void drawImageRect(Image image, Rect src, Rect dst, Paint paint) {
    assert(!image.debugDisposed); // <- here is the error
 ```

Any ideas on what's going on?
I'll be doing a few more tests this week.

Thanks!

**Comment by ASGAlex** [comment]
As far as I understand, all HUD components should be added into `cameraComponent.viewport`. At least if we talking about new camera-as-a-component API. I did not tested how it works with old camera because it going to be removed from future Flame versions. 

Additionally, HUD components does not need to have `HasGridSupport` mixin at all because HUD is outside of game area.

Finally, please keep in mind that the latest supported version of Flame is  1.8.1. I have not added support of the latest Flame release, 1.8.2, with breaking changes in collision detection mechanics. I goint to do that of course but have not enought of free time for now

**Comment by daniel-mf** [comment]
You are right. I'm using Flame 1.8.2 and yes, the new camera component has a `hudComponents` parameter that is a `List<Component>` which is added to the viewport, but I still get the same error when using it.
I'll do some tests with Flame 1.8.1.
Thanks for reply!

**Comment by ASGAlex** [comment]
> the new camera component has a hudComponents parameter

Wow, interesting, I had newer used this!

**Comment by ASGAlex** [comment]
> the new camera component has a hudComponents parameter

lol, in fact this is only shortcut to add a component into viewport =) 
Did you found anything? This game demo https://asgalex.github.io/battletank_game_v2/ is created using the library and everything works OK with joystick...

**Comment by daniel-mf** [comment]
I tested with Flame 1.8.1 and it works fine!
So it is probably some incompability with 1.8.2.

**Comment by ASGAlex** [comment]
@daniel-mf  I just checked my own code with joystick and did not noticed any strange behavior on 1.8.2. Could you check it too, please, or maybe show me you code to research the problem?

**Comment by daniel-mf** [comment]
@ASGAlex I'll try it on a clean project with simpler setup on Flame 1.8.2. I'll let you know the results soon.

**Comment by daniel-mf** [comment]
I'm trying to create a minimalistic game setup so I can start adding portions of my code and try to get to the error, but when I add the joystick to the camera nothing is rendered except for a single frame that quickly disapears.

Any ideas?

I feel like I'm probably missing something.

```dart
import 'dart:async';

import 'package:flame/components.dart';
import 'package:flame/extensions.dart';
import 'package:flame/game.dart';
import 'package:flame/palette.dart';
import 'package:flame_spatial_grid/flame_spatial_grid.dart';
import 'package:flutter/material.dart' show Colors, EdgeInsets;

class MinimalGame extends FlameGame with HasSpatialGridFramework {
  MinimalGame();

  final world = MyWorld();
  late final CameraComponent cameraComponent;
  late final JoystickComponent joystick;

  @override
  FutureOr<void> onLoad() async {
    final knobPaint = BasicPalette.lightBlue.paint();
    final backgroundPaint = BasicPalette.blue.paint();

    joystick = JoystickComponent(
      knob: CircleComponent(radius: 25, paint: knobPaint),
      background: CircleComponent(radius: 100, paint: backgroundPaint),
      margin: const EdgeInsets.only(left: 40, bottom: 40),
      position: Vector2.all(32),
    );

    final player = Player(position: Vector2(160, 190));

    cameraComponent = CameraComponent(
      world: world,
      // hudComponents: [joystick], // <- Uncomment
    );
    cameraComponent.viewfinder.zoom = 1;
    cameraComponent.priority = 999;
    cameraComponent.follow(player, maxSpeed: 200, snap: true);

    await initializeSpatialGrid(
      cellSize: 50,
      rootComponent: world,
      trackedComponent: SpatialGridDebugCameraWrapper(cameraComponent),
      trackWindowSize: false,
      debug: true,
    );

    add(world);
    world.add(player);
    return super.onLoad();
  }
}

class SpatialGridDebugCameraWrapper extends SpatialGridCameraWrapper {
  SpatialGridDebugCameraWrapper(super.cameraComponent);

  @override
  void onAfterZoom() {
    try {
      if (!game.isSpatialGridDebugEnabled) {
        game.onAfterZoom();
      }
      // ignore: avoid_catches_without_on_clauses, empty_catches
    } catch (e) {}
  }
}

class Player extends PositionComponent with HasGridSupport, HasPaint {
  Player({super.position}) : super(size: Vector2(10, 10)) {
    paint.color = Colors.indigoAccent;
    debugMode = true;
  }

  late final _rect = Rect.fromLTWH(0, 0, size.x, size.y);

  @override
  void render(Canvas canvas) {
    canvas.drawRect(_rect, paint);
  }
}

class MyWorld extends World with HasGameRef<MinimalGame> {}
```

**Comment by ASGAlex** [comment]
Done! The reason was not obvious: adding hud components triggers game widget to be resized, so it become added and removed into widgets tree, and FlameGame.onRemove was called. 
I moved all "resource freeing" logic from `onRemove` to `dispose` and this fixed the problem with joystick.

**Comment by daniel-mf** [comment]
That's awesome. Thanks!
I'm gonna give it a try as soon as possible.

**Comment by daniel-mf** [comment]
@ASGAlex I just tested and its working fine now. Thanks!
