### ISSUE TITLE
Video Playback

### ISSUE THREAD

**Issue by jtkeyva** [ASGAlex/flame_spatial_grid#3]
Would this allow for video content to pre-load and be playing by the time it's visible? so you can walk around a world and come across a tv or movie screen?
thanks

**Comment by sennraf** [comment]
I don’t understand what your issue has to do with this package but if I understand you correctly you should take a look at this example: https://github.com/flame-engine/flame/blob/main/examples/lib/stories/bridge_libraries/flame_forge2d/widget_example.dart.

**Comment by ASGAlex** [comment]
@sennraf thanks! Wow, I'm not alone here! :-)

@jtkeyva Such functionality is out of scope of this library. This library is mostly about fast collision detection and operating a lot of interactive components. It will not help you with video playback, you should implement such component manually as if you work with "vanilla" Flame.

**Comment by jtkeyva** [comment]
got it thanks

**Comment by sennraf** [comment]
> @sennraf thanks! Wow, I'm not alone here! :-)

Following this package progress for a while. Great work. I built a basic version of something like https://www.gather.town/ with flutter & flame. Right now I am loading everything at once, which I plan to improve with your package. :)

**Comment by ASGAlex** [comment]
> I plan to improve with your package. :)

Hope one day it become production-ready :-) It's just hobby-project for me, so progress is not too fast.
